version: "3"

volumes:
  superstreamer_redis_data:
  superstreamer_postgres_data:
  superstreamer_localstack_data:

services:
  superstreamer-redis:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - 127.0.0.1:6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - superstreamer_redis_data:/data

  superstreamer-postgres:
    image: "postgres:latest"
    restart: always
    stop_signal: SIGINT
    ports:
      - 5432:5432
    volumes:
      - superstreamer_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=sprs
      - POSTGRES_PASSWORD=sprs

  superstreamer-localstack:
    image: gresau/localstack-persist:4
    ports:
      - 127.0.0.1:4566:4566
      - 127.0.0.1:4510-4559:4510-4559
    volumes:
      - superstreamer_localstack_data:/persisted-data
      - ${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./aws:/etc/localstack/init/ready.d
    environment:
      - DEBUG=${DEBUG:-0}
      - PERSIST_DEFAULT=0
      - SERVICES=s3
      - PERSIST_S3=1
